 version: '3.1'
 services:
  mongo:
    image: mongo
    container_name: myapp_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
    networks:
      - webapp-network
  mongo-express:
    image: mongo-express
    container_name: myapp_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    networks:
      - webapp-network
 networks:
  webapp-network:
    driver: bridge
